AWSTemplateFormatVersion: 2010-09-09
Description: >-
  taskhub-restapi-backend-repo
Transform:
  - AWS::Serverless-2016-10-31
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  TaskHubApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Name: TaskHub
      Auth:
        ApiKeyRequired: true
  TaskHubApiKey:
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Name: TaskHubApiKey
      Description: API Key for TaskHub API
      Enabled: true

  # Create a Usage Plan
  TaskHubUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: TaskHubUsagePlan
      Description: Usage plan for TaskHub API
      ApiStages:
        - ApiId: !Ref TaskHubApiGatewayApi
          Stage: Dev
      Quota:
        Limit: 5000
        Period: MONTH
      Throttle:
        BurstLimit: 10
        RateLimit: 5

  # Associate the API Key with the Usage Plan
  TaskHubUsagePlanKey:
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref TaskHubApiKey
      KeyType: API_KEY
      UsagePlanId: !Ref TaskHubUsagePlan

  TaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: TaskHandler
      Handler: TaskHandler.TasksLambdaHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      CodeUri: ./src/handlers/
      Policies:
        - DynamoDBCrudPolicy:
            TableName: task
        - Statement:
            - Effect: Allow
              Action:
                - dynamodb:Query
                - dynamodb:Scan
                - dynamodb:PutItem
                - dynamodb:DeleteItem
                - dynamodb:UpdateItem
              Resource:
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/task"
                - !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/task/index/*"
      Events:
        GetTasksByUserId:
          Type: Api
          Properties:
            RestApiId: !Ref TaskHubApiGatewayApi
            Path: /tasks/{UserId} # this api will list all the tasks created by the perticular user
            Method: GET
        CreateTask:
          Type: Api
          Properties:
            RestApiId: !Ref TaskHubApiGatewayApi
            Path: /tasks # from this api we can create the task
            Method: POST
