AWSTemplateFormatVersion: 2010-09-09
Description: >-
  taskhub-restapi-backend-repo
Transform:
  - AWS::Serverless-2016-10-31
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    LoggingConfig:
      LogFormat: JSON

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Name: RestFul Crud api

  EmployeeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetEmployeesById
      Handler: EmployeeResource.employeeHandler
      Runtime: nodejs20.x
      Architectures:
        - x86_64
      CodeUri: ./src/handlers/
      Events:
        GetApi:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /employee/{id}
            Method: GET
        CreateEmployee:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /employee
            Method: POST
        UpdateEmployee:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /employee/{id}
            Method: PUT
        DeleteEmployee:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /employee/{id}
            Method: DELETE
      Environment:
        Variables:
          DYNAMODB_TABLE: EmployeeTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: EmployeeTable

  EmployeesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: EmployeeId
        Type: String
      TableName: EmployeeTable
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2
